export const TOGGLE_MORE_OPTIONS = "TOGGLE_MORE_OPTIONS";
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
export const ADD_EMPTY_NOTE = "ADD_NOTE";
export const SAVE_NOTE = "SAVE_NOTE";
export const SET_NOTE_TO_EDIT = "SET_NOTE_TO_EDIT";
export const ALL_NOTES_SELECTED = "ALL_NOTES_SELECTED";
export const FAVOURITE_NOTES_SELECTED = "FAVOURITE_NOTES_SELECTED";
export const RECYCLE_BIN_SELECTED = "RECYCLE_BIN_SELECTED";
